/* eslint-disable */
// @ts-nocheck
// AUTO-GENERATED by scripts/precompile-emails.mjs — DO NOT EDIT BY HAND.
// Handlebars templates precompiled to specs so the Worker never calls new Function()
// (Cloudflare Workers forbid runtime code generation). Rendered via handlebars/runtime.
import Handlebars from "handlebars/runtime";
import type { Locale, TemplateKey } from "./templates";

export const BASE = Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<!DOCTYPE html>\n<html lang=\""
    + alias4(((helper = (helper = lookupProperty(helpers,"locale") || (depth0 != null ? lookupProperty(depth0,"locale") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"locale","hash":{},"data":data,"loc":{"start":{"line":2,"column":12},"end":{"line":2,"column":22}}}) : helper)))
    + "\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n  <title>"
    + alias4(((helper = (helper = lookupProperty(helpers,"subject") || (depth0 != null ? lookupProperty(depth0,"subject") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"subject","hash":{},"data":data,"loc":{"start":{"line":6,"column":9},"end":{"line":6,"column":20}}}) : helper)))
    + "</title>\n  <style>\n    body { margin: 0; padding: 0; font-family: \"IBM Plex Sans\", Arial, Helvetica, sans-serif; }\n    img { max-width: 100%; height: auto; border: 0; }\n    table { border-collapse: collapse; }\n    .email-container { width: 100%; max-width: 600px; }\n    /* Mobile-first: the container is fluid and never wider than the screen, so\n       small viewports fit without horizontal scrolling. */\n    @media only screen and (max-width: 600px) {\n      .email-container { width: 100% !important; }\n      .email-body { padding: 16px !important; }\n      .email-gutter { padding-left: 12px !important; padding-right: 12px !important; }\n    }\n  </style>\n</head>\n<body style=\"margin: 0; padding: 0; background-color: #f7f9fb;\">\n  <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width: 100%; background-color: #f7f9fb;\">\n    <tr>\n      <td align=\"center\" class=\"email-gutter\" style=\"padding: 20px 12px;\">\n        <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" class=\"email-container\" style=\"width: 100%; max-width: 600px; background-color: white; border-collapse: collapse;\">\n"
    + ((stack1 = container.invokePartial(lookupProperty(partials,"header"),depth0,{"name":"header","data":data,"indent":"          ","helpers":helpers,"partials":partials,"decorators":container.decorators})) != null ? stack1 : "")
    + "          <tr>\n            <td class=\"email-body\" style=\"padding: 20px; color: #2d3133; font-size: 14px; line-height: 1.6;\">\n"
    + ((stack1 = container.invokePartial(lookupProperty(partials,"body"),depth0,{"name":"body","data":data,"indent":"              ","helpers":helpers,"partials":partials,"decorators":container.decorators})) != null ? stack1 : "")
    + "            </td>\n          </tr>\n"
    + ((stack1 = container.invokePartial(lookupProperty(partials,"footer"),depth0,{"name":"footer","data":data,"indent":"          ","helpers":helpers,"partials":partials,"decorators":container.decorators})) != null ? stack1 : "")
    + "        </table>\n      </td>\n    </tr>\n  </table>\n</body>\n</html>\n";
},"usePartial":true,"useData":true});

export const PARTIALS: Record<Locale, { header: HandlebarsTemplateDelegate; footer: HandlebarsTemplateDelegate }> = {
  fr: { header: Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<tr>\n  <td style=\"background-color: #9d4300; padding: 20px; text-align: center;\">\n    <div style=\"color: white; font-size: 24px; font-weight: bold;\">\n      L'Auberge du Vieux Pont\n    </div>\n    <div style=\"color: #f0e5d8; font-size: 14px; margin-top: 4px;\">\n      Gîte champêtre en Mauricie\n    </div>\n  </td>\n</tr>\n";
},"useData":true}), footer: Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<tr>\n  <td style=\"background-color: #f7f9fb; padding: 20px; border-top: 1px solid #e8ebed; text-align: center; font-size: 12px; color: #2d3133; line-height: 1.6;\">\n    <div style=\"margin-bottom: 12px;\">\n      <strong>L'Auberge du Vieux Pont</strong><br/>\n      111, avenue Saint-Michel<br/>\n      Saint-Raymond (Québec) G3L 0H8<br/>\n      Canada\n    </div>\n    <div style=\"margin-bottom: 12px;\">\n      <a href=\""
    + alias4(((helper = (helper = lookupProperty(helpers,"contactPhoneHref") || (depth0 != null ? lookupProperty(depth0,"contactPhoneHref") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"contactPhoneHref","hash":{},"data":data,"loc":{"start":{"line":10,"column":15},"end":{"line":10,"column":35}}}) : helper)))
    + "\" style=\"color: #9d4300; text-decoration: none;\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"contactPhone") || (depth0 != null ? lookupProperty(depth0,"contactPhone") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"contactPhone","hash":{},"data":data,"loc":{"start":{"line":10,"column":84},"end":{"line":10,"column":100}}}) : helper)))
    + "</a><br/>\n      <a href=\"mailto:"
    + alias4(((helper = (helper = lookupProperty(helpers,"contactEmail") || (depth0 != null ? lookupProperty(depth0,"contactEmail") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"contactEmail","hash":{},"data":data,"loc":{"start":{"line":11,"column":22},"end":{"line":11,"column":38}}}) : helper)))
    + "\" style=\"color: #9d4300; text-decoration: none;\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"contactEmail") || (depth0 != null ? lookupProperty(depth0,"contactEmail") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"contactEmail","hash":{},"data":data,"loc":{"start":{"line":11,"column":87},"end":{"line":11,"column":103}}}) : helper)))
    + "</a>\n    </div>\n    <div style=\"color: #304542; margin-bottom: 12px;\">\n      <strong>CITQ #304542</strong>\n    </div>\n    <div style=\"font-size: 11px; color: #6b7c81;\">\n      © 2026 L'Auberge du Vieux Pont. Tous droits réservés.\n    </div>\n  </td>\n</tr>\n";
},"useData":true}) },
  en: { header: Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<tr>\n  <td style=\"background-color: #9d4300; padding: 20px; text-align: center;\">\n    <div style=\"color: white; font-size: 24px; font-weight: bold;\">\n      L'Auberge du Vieux Pont\n    </div>\n    <div style=\"color: #f0e5d8; font-size: 14px; margin-top: 4px;\">\n      Rural inn in Mauricie\n    </div>\n  </td>\n</tr>\n";
},"useData":true}), footer: Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<tr>\n  <td style=\"background-color: #f7f9fb; padding: 20px; border-top: 1px solid #e8ebed; text-align: center; font-size: 12px; color: #2d3133; line-height: 1.6;\">\n    <div style=\"margin-bottom: 12px;\">\n      <strong>L'Auberge du Vieux Pont</strong><br/>\n      111, avenue Saint-Michel<br/>\n      Saint-Raymond (Quebec) G3L 0H8<br/>\n      Canada\n    </div>\n    <div style=\"margin-bottom: 12px;\">\n      <a href=\""
    + alias4(((helper = (helper = lookupProperty(helpers,"contactPhoneHref") || (depth0 != null ? lookupProperty(depth0,"contactPhoneHref") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"contactPhoneHref","hash":{},"data":data,"loc":{"start":{"line":10,"column":15},"end":{"line":10,"column":35}}}) : helper)))
    + "\" style=\"color: #9d4300; text-decoration: none;\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"contactPhone") || (depth0 != null ? lookupProperty(depth0,"contactPhone") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"contactPhone","hash":{},"data":data,"loc":{"start":{"line":10,"column":84},"end":{"line":10,"column":100}}}) : helper)))
    + "</a><br/>\n      <a href=\"mailto:"
    + alias4(((helper = (helper = lookupProperty(helpers,"contactEmail") || (depth0 != null ? lookupProperty(depth0,"contactEmail") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"contactEmail","hash":{},"data":data,"loc":{"start":{"line":11,"column":22},"end":{"line":11,"column":38}}}) : helper)))
    + "\" style=\"color: #9d4300; text-decoration: none;\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"contactEmail") || (depth0 != null ? lookupProperty(depth0,"contactEmail") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"contactEmail","hash":{},"data":data,"loc":{"start":{"line":11,"column":87},"end":{"line":11,"column":103}}}) : helper)))
    + "</a>\n    </div>\n    <div style=\"color: #304542; margin-bottom: 12px;\">\n      <strong>CITQ #304542</strong>\n    </div>\n    <div style=\"font-size: 11px; color: #6b7c81;\">\n      © 2026 L'Auberge du Vieux Pont. All rights reserved.\n    </div>\n  </td>\n</tr>\n";
},"useData":true}) },
};

export const TEMPLATES: Record<TemplateKey, Record<Locale, HandlebarsTemplateDelegate>> = {
  "welcome": { fr: Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<p>Bienvenue, "
    + alias4(((helper = (helper = lookupProperty(helpers,"firstName") || (depth0 != null ? lookupProperty(depth0,"firstName") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"firstName","hash":{},"data":data,"loc":{"start":{"line":1,"column":14},"end":{"line":1,"column":27}}}) : helper)))
    + " !</p>\n\n<p>Nous sommes ravis de vous accueillir à L'Auberge du Vieux Pont. Votre compte a été créé avec succès.</p>\n\n<p>Pour commencer, veuillez vous connecter à l'adresse suivante :</p>\n\n<p style=\"text-align: center; margin: 20px 0;\">\n  <a href=\""
    + alias4(((helper = (helper = lookupProperty(helpers,"loginUrl") || (depth0 != null ? lookupProperty(depth0,"loginUrl") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"loginUrl","hash":{},"data":data,"loc":{"start":{"line":8,"column":11},"end":{"line":8,"column":23}}}) : helper)))
    + "\" style=\"display: inline-block; padding: 12px 30px; background-color: #9d4300; color: white; text-decoration: none; border-radius: 4px; font-weight: bold;\">Se connecter</a>\n</p>\n\n<p>Si vous avez des questions, n'hésitez pas à nous contacter.</p>\n\n<p>Cordialement,<br/>\nL'équipe du Vieux Pont</p>\n";
},"useData":true}), en: Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<p>Welcome, "
    + alias4(((helper = (helper = lookupProperty(helpers,"firstName") || (depth0 != null ? lookupProperty(depth0,"firstName") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"firstName","hash":{},"data":data,"loc":{"start":{"line":1,"column":12},"end":{"line":1,"column":25}}}) : helper)))
    + " !</p>\n\n<p>We are delighted to welcome you to L'Auberge du Vieux Pont. Your account has been successfully created.</p>\n\n<p>To get started, please log in at the following address:</p>\n\n<p style=\"text-align: center; margin: 20px 0;\">\n  <a href=\""
    + alias4(((helper = (helper = lookupProperty(helpers,"loginUrl") || (depth0 != null ? lookupProperty(depth0,"loginUrl") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"loginUrl","hash":{},"data":data,"loc":{"start":{"line":8,"column":11},"end":{"line":8,"column":23}}}) : helper)))
    + "\" style=\"display: inline-block; padding: 12px 30px; background-color: #9d4300; color: white; text-decoration: none; border-radius: 4px; font-weight: bold;\">Log in</a>\n</p>\n\n<p>If you have any questions, please don't hesitate to contact us.</p>\n\n<p>Best regards,<br/>\nThe Vieux Pont team</p>\n";
},"useData":true}) },
  "password-reset": { fr: Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<p>Bonjour "
    + alias4(((helper = (helper = lookupProperty(helpers,"firstName") || (depth0 != null ? lookupProperty(depth0,"firstName") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"firstName","hash":{},"data":data,"loc":{"start":{"line":1,"column":11},"end":{"line":1,"column":24}}}) : helper)))
    + ",</p>\n\n<p>Vous avez demandé la réinitialisation de votre mot de passe. Ce lien expire dans "
    + alias4(((helper = (helper = lookupProperty(helpers,"expiryHours") || (depth0 != null ? lookupProperty(depth0,"expiryHours") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"expiryHours","hash":{},"data":data,"loc":{"start":{"line":3,"column":84},"end":{"line":3,"column":99}}}) : helper)))
    + " heures.</p>\n\n<p style=\"text-align: center; margin: 20px 0;\">\n  <a href=\""
    + alias4(((helper = (helper = lookupProperty(helpers,"resetUrl") || (depth0 != null ? lookupProperty(depth0,"resetUrl") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"resetUrl","hash":{},"data":data,"loc":{"start":{"line":6,"column":11},"end":{"line":6,"column":23}}}) : helper)))
    + "\" style=\"display: inline-block; padding: 12px 30px; background-color: #9d4300; color: white; text-decoration: none; border-radius: 4px; font-weight: bold;\">Réinitialiser le mot de passe</a>\n</p>\n\n<p>Si vous n'avez pas demandé cette réinitialisation, vous pouvez ignorer ce message.</p>\n\n<p>Cordialement,<br/>\nL'équipe du Vieux Pont</p>\n";
},"useData":true}), en: Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<p>Hello "
    + alias4(((helper = (helper = lookupProperty(helpers,"firstName") || (depth0 != null ? lookupProperty(depth0,"firstName") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"firstName","hash":{},"data":data,"loc":{"start":{"line":1,"column":9},"end":{"line":1,"column":22}}}) : helper)))
    + ",</p>\n\n<p>You have requested to reset your password. This link expires in "
    + alias4(((helper = (helper = lookupProperty(helpers,"expiryHours") || (depth0 != null ? lookupProperty(depth0,"expiryHours") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"expiryHours","hash":{},"data":data,"loc":{"start":{"line":3,"column":67},"end":{"line":3,"column":82}}}) : helper)))
    + " hours.</p>\n\n<p style=\"text-align: center; margin: 20px 0;\">\n  <a href=\""
    + alias4(((helper = (helper = lookupProperty(helpers,"resetUrl") || (depth0 != null ? lookupProperty(depth0,"resetUrl") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"resetUrl","hash":{},"data":data,"loc":{"start":{"line":6,"column":11},"end":{"line":6,"column":23}}}) : helper)))
    + "\" style=\"display: inline-block; padding: 12px 30px; background-color: #9d4300; color: white; text-decoration: none; border-radius: 4px; font-weight: bold;\">Reset Password</a>\n</p>\n\n<p>If you didn't request this password reset, you can ignore this message.</p>\n\n<p>Best regards,<br/>\nThe Vieux Pont team</p>\n";
},"useData":true}) },
  "reservation-confirmation": { fr: Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<p>Merci pour votre réservation, "
    + alias4(((helper = (helper = lookupProperty(helpers,"name") || (depth0 != null ? lookupProperty(depth0,"name") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"name","hash":{},"data":data,"loc":{"start":{"line":1,"column":33},"end":{"line":1,"column":41}}}) : helper)))
    + " !</p>\n\n<p>Voici les détails de votre réservation :</p>\n\n<div style=\"background-color: #f0f0f0; padding: 15px; border-radius: 4px; margin: 20px 0;\">\n  <p style=\"margin: 0 0 10px 0;\"><strong>Numéro de confirmation :</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"confirmationCode") || (depth0 != null ? lookupProperty(depth0,"confirmationCode") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"confirmationCode","hash":{},"data":data,"loc":{"start":{"line":6,"column":75},"end":{"line":6,"column":95}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Chambre :</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"roomLabel") || (depth0 != null ? lookupProperty(depth0,"roomLabel") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"roomLabel","hash":{},"data":data,"loc":{"start":{"line":7,"column":60},"end":{"line":7,"column":73}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Arrivée :</strong> "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkIn") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":8,"column":60},"end":{"line":8,"column":82}}}))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Départ :</strong> "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkOut") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":9,"column":59},"end":{"line":9,"column":82}}}))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Nombre de nuits :</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"nights") || (depth0 != null ? lookupProperty(depth0,"nights") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"nights","hash":{},"data":data,"loc":{"start":{"line":10,"column":68},"end":{"line":10,"column":78}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Nombre de personnes :</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"guests") || (depth0 != null ? lookupProperty(depth0,"guests") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"guests","hash":{},"data":data,"loc":{"start":{"line":11,"column":72},"end":{"line":11,"column":82}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0;\"><strong>Tarif par nuit :</strong> "
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"nightlyPrice") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":12,"column":58},"end":{"line":12,"column":80}}}))
    + "</p>\n</div>\n\n<p><strong>Détails du prix :</strong></p>\n\n<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width: 100%; border-collapse: collapse; margin: 20px 0;\">\n  <tr style=\"border-bottom: 2px solid #333;\">\n    <td style=\"padding: 8px; font-weight: bold;\">Sous-total</td>\n    <td style=\"text-align: right; padding: 8px; font-weight: bold;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"subtotal") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":20,"column":68},"end":{"line":20,"column":86}}}))
    + "</td>\n  </tr>\n  <tr style=\"border-bottom: 1px solid #ddd;\">\n    <td style=\"padding: 8px;\">Taxe d'hébergement (3.5%)</td>\n    <td style=\"text-align: right; padding: 8px;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"accommodationTax") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":24,"column":49},"end":{"line":24,"column":75}}}))
    + "</td>\n  </tr>\n  <tr style=\"border-bottom: 1px solid #ddd;\">\n    <td style=\"padding: 8px;\">TPS (5%)</td>\n    <td style=\"text-align: right; padding: 8px;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"tps") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":28,"column":49},"end":{"line":28,"column":62}}}))
    + "</td>\n  </tr>\n  <tr style=\"border-bottom: 2px solid #333;\">\n    <td style=\"padding: 8px;\">TVQ (9.975%)</td>\n    <td style=\"text-align: right; padding: 8px;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"tvq") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":32,"column":49},"end":{"line":32,"column":62}}}))
    + "</td>\n  </tr>\n  <tr>\n    <td style=\"padding: 8px; font-weight: bold; font-size: 16px;\">Total (taxes incluses)</td>\n    <td style=\"text-align: right; padding: 8px; font-weight: bold; font-size: 16px;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"total") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":36,"column":85},"end":{"line":36,"column":100}}}))
    + "</td>\n  </tr>\n</table>\n\n<p style=\"color: #45464d; font-size: 13px;\">Les taxes applicables (taxe d'hébergement, TPS et TVQ) sont incluses dans le total ci-dessus.</p>\n\n<p>Vous pouvez gérer votre réservation en cliquant sur le lien ci-dessous :</p>\n\n<p style=\"text-align: center; margin: 20px 0;\">\n  <a href=\""
    + alias4(((helper = (helper = lookupProperty(helpers,"manageUrl") || (depth0 != null ? lookupProperty(depth0,"manageUrl") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"manageUrl","hash":{},"data":data,"loc":{"start":{"line":45,"column":11},"end":{"line":45,"column":24}}}) : helper)))
    + "\" style=\"display: inline-block; padding: 12px 30px; background-color: #9d4300; color: white; text-decoration: none; border-radius: 4px; font-weight: bold;\">Gérer ma réservation</a>\n</p>\n\n<p>Nous avons hâte de vous accueillir !</p>\n\n<p>Cordialement,<br/>\nL'équipe du Vieux Pont</p>\n";
},"useData":true}), en: Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<p>Thank you for your reservation, "
    + alias4(((helper = (helper = lookupProperty(helpers,"name") || (depth0 != null ? lookupProperty(depth0,"name") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"name","hash":{},"data":data,"loc":{"start":{"line":1,"column":35},"end":{"line":1,"column":43}}}) : helper)))
    + " !</p>\n\n<p>Here are your reservation details:</p>\n\n<div style=\"background-color: #f0f0f0; padding: 15px; border-radius: 4px; margin: 20px 0;\">\n  <p style=\"margin: 0 0 10px 0;\"><strong>Confirmation code:</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"confirmationCode") || (depth0 != null ? lookupProperty(depth0,"confirmationCode") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"confirmationCode","hash":{},"data":data,"loc":{"start":{"line":6,"column":69},"end":{"line":6,"column":89}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Room:</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"roomLabel") || (depth0 != null ? lookupProperty(depth0,"roomLabel") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"roomLabel","hash":{},"data":data,"loc":{"start":{"line":7,"column":56},"end":{"line":7,"column":69}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Check-in:</strong> "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkIn") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":8,"column":60},"end":{"line":8,"column":82}}}))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Check-out:</strong> "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkOut") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":9,"column":61},"end":{"line":9,"column":84}}}))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Number of nights:</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"nights") || (depth0 != null ? lookupProperty(depth0,"nights") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"nights","hash":{},"data":data,"loc":{"start":{"line":10,"column":68},"end":{"line":10,"column":78}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Number of guests:</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"guests") || (depth0 != null ? lookupProperty(depth0,"guests") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"guests","hash":{},"data":data,"loc":{"start":{"line":11,"column":68},"end":{"line":11,"column":78}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0;\"><strong>Rate per night:</strong> "
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"nightlyPrice") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":12,"column":57},"end":{"line":12,"column":79}}}))
    + "</p>\n</div>\n\n<p><strong>Price details:</strong></p>\n\n<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width: 100%; border-collapse: collapse; margin: 20px 0;\">\n  <tr style=\"border-bottom: 2px solid #333;\">\n    <td style=\"padding: 8px; font-weight: bold;\">Subtotal</td>\n    <td style=\"text-align: right; padding: 8px; font-weight: bold;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"subtotal") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":20,"column":68},"end":{"line":20,"column":86}}}))
    + "</td>\n  </tr>\n  <tr style=\"border-bottom: 1px solid #ddd;\">\n    <td style=\"padding: 8px;\">Lodging tax (3.5%)</td>\n    <td style=\"text-align: right; padding: 8px;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"accommodationTax") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":24,"column":49},"end":{"line":24,"column":75}}}))
    + "</td>\n  </tr>\n  <tr style=\"border-bottom: 1px solid #ddd;\">\n    <td style=\"padding: 8px;\">GST (5%)</td>\n    <td style=\"text-align: right; padding: 8px;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"tps") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":28,"column":49},"end":{"line":28,"column":62}}}))
    + "</td>\n  </tr>\n  <tr style=\"border-bottom: 2px solid #333;\">\n    <td style=\"padding: 8px;\">QST (9.975%)</td>\n    <td style=\"text-align: right; padding: 8px;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"tvq") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":32,"column":49},"end":{"line":32,"column":62}}}))
    + "</td>\n  </tr>\n  <tr>\n    <td style=\"padding: 8px; font-weight: bold; font-size: 16px;\">Total (taxes included)</td>\n    <td style=\"text-align: right; padding: 8px; font-weight: bold; font-size: 16px;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"total") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":36,"column":85},"end":{"line":36,"column":100}}}))
    + "</td>\n  </tr>\n</table>\n\n<p style=\"color: #45464d; font-size: 13px;\">Applicable taxes (lodging tax, GST and QST) are included in the total above.</p>\n\n<p>You can manage your reservation by clicking the link below:</p>\n\n<p style=\"text-align: center; margin: 20px 0;\">\n  <a href=\""
    + alias4(((helper = (helper = lookupProperty(helpers,"manageUrl") || (depth0 != null ? lookupProperty(depth0,"manageUrl") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"manageUrl","hash":{},"data":data,"loc":{"start":{"line":45,"column":11},"end":{"line":45,"column":24}}}) : helper)))
    + "\" style=\"display: inline-block; padding: 12px 30px; background-color: #9d4300; color: white; text-decoration: none; border-radius: 4px; font-weight: bold;\">Manage my reservation</a>\n</p>\n\n<p>We look forward to welcoming you!</p>\n\n<p>Best regards,<br/>\nThe Vieux Pont team</p>\n";
},"useData":true}) },
  "reservation-cancellation": { fr: Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<p>Bonjour "
    + alias4(((helper = (helper = lookupProperty(helpers,"name") || (depth0 != null ? lookupProperty(depth0,"name") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"name","hash":{},"data":data,"loc":{"start":{"line":1,"column":11},"end":{"line":1,"column":19}}}) : helper)))
    + ",</p>\n\n<p>Votre réservation a été annulée.</p>\n\n<div style=\"background-color: #f0f0f0; padding: 15px; border-radius: 4px; margin: 20px 0;\">\n  <p style=\"margin: 0 0 10px 0;\"><strong>Numéro de confirmation :</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"confirmationCode") || (depth0 != null ? lookupProperty(depth0,"confirmationCode") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"confirmationCode","hash":{},"data":data,"loc":{"start":{"line":6,"column":75},"end":{"line":6,"column":95}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Dates :</strong> "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkIn") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":7,"column":58},"end":{"line":7,"column":80}}}))
    + " - "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkOut") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":7,"column":83},"end":{"line":7,"column":106}}}))
    + "</p>\n</div>\n\n<p>Si vous avez besoin de renseignements supplémentaires, veuillez contacter :</p>\n\n<p style=\"text-align: center; margin: 20px 0;\">\n  <a href=\"mailto:"
    + alias4(((helper = (helper = lookupProperty(helpers,"contactEmail") || (depth0 != null ? lookupProperty(depth0,"contactEmail") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"contactEmail","hash":{},"data":data,"loc":{"start":{"line":13,"column":18},"end":{"line":13,"column":34}}}) : helper)))
    + "\" style=\"color: #9d4300; text-decoration: none;\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"contactEmail") || (depth0 != null ? lookupProperty(depth0,"contactEmail") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"contactEmail","hash":{},"data":data,"loc":{"start":{"line":13,"column":83},"end":{"line":13,"column":99}}}) : helper)))
    + "</a>\n</p>\n\n<p>Merci de votre compréhension.</p>\n\n<p>Cordialement,<br/>\nL'équipe du Vieux Pont</p>\n";
},"useData":true}), en: Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<p>Hello "
    + alias4(((helper = (helper = lookupProperty(helpers,"name") || (depth0 != null ? lookupProperty(depth0,"name") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"name","hash":{},"data":data,"loc":{"start":{"line":1,"column":9},"end":{"line":1,"column":17}}}) : helper)))
    + ",</p>\n\n<p>Your reservation has been cancelled.</p>\n\n<div style=\"background-color: #f0f0f0; padding: 15px; border-radius: 4px; margin: 20px 0;\">\n  <p style=\"margin: 0 0 10px 0;\"><strong>Confirmation code:</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"confirmationCode") || (depth0 != null ? lookupProperty(depth0,"confirmationCode") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"confirmationCode","hash":{},"data":data,"loc":{"start":{"line":6,"column":69},"end":{"line":6,"column":89}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0;\"><strong>Dates:</strong> "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkIn") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":7,"column":48},"end":{"line":7,"column":70}}}))
    + " - "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkOut") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":7,"column":73},"end":{"line":7,"column":96}}}))
    + "</p>\n</div>\n\n<p>If you need further information, please contact:</p>\n\n<p style=\"text-align: center; margin: 20px 0;\">\n  <a href=\"mailto:"
    + alias4(((helper = (helper = lookupProperty(helpers,"contactEmail") || (depth0 != null ? lookupProperty(depth0,"contactEmail") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"contactEmail","hash":{},"data":data,"loc":{"start":{"line":13,"column":18},"end":{"line":13,"column":34}}}) : helper)))
    + "\" style=\"color: #9d4300; text-decoration: none;\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"contactEmail") || (depth0 != null ? lookupProperty(depth0,"contactEmail") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"contactEmail","hash":{},"data":data,"loc":{"start":{"line":13,"column":83},"end":{"line":13,"column":99}}}) : helper)))
    + "</a>\n</p>\n\n<p>Thank you for your understanding.</p>\n\n<p>Best regards,<br/>\nThe Vieux Pont team</p>\n";
},"useData":true}) },
  "invoice-receipt": { fr: Handlebars.template({"0":function(container,depth0,helpers,partials,data) {
    var alias1=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "  <tr style=\"border-bottom: 1px solid #ddd;\">\n    <td style=\"padding: 8px;\">"
    + alias1(container.lambda((depth0 != null ? lookupProperty(depth0,"description") : depth0), depth0))
    + "</td>\n    <td style=\"text-align: right; padding: 8px;\">"
    + alias1((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||container.hooks.helperMissing).call(depth0 != null ? depth0 : (container.nullContext || {}),(depth0 != null ? lookupProperty(depth0,"amount") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":21,"column":49},"end":{"line":21,"column":70}}}))
    + "</td>\n  </tr>\n";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<p>Merci pour votre paiement, "
    + alias4(((helper = (helper = lookupProperty(helpers,"name") || (depth0 != null ? lookupProperty(depth0,"name") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"name","hash":{},"data":data,"loc":{"start":{"line":1,"column":30},"end":{"line":1,"column":38}}}) : helper)))
    + " !</p>\n\n<p>Voici votre reçu de facture :</p>\n\n<div style=\"background-color: #f0f0f0; padding: 15px; border-radius: 4px; margin: 20px 0;\">\n  <p style=\"margin: 0 0 10px 0;\"><strong>Numéro de facture :</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"invoiceNumber") || (depth0 != null ? lookupProperty(depth0,"invoiceNumber") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"invoiceNumber","hash":{},"data":data,"loc":{"start":{"line":6,"column":70},"end":{"line":6,"column":87}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Dates :</strong> "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkIn") : depth0),(depth0 != null ? lookupProperty(depth0,"locale") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":7,"column":58},"end":{"line":7,"column":87}}}))
    + " - "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkOut") : depth0),(depth0 != null ? lookupProperty(depth0,"locale") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":7,"column":90},"end":{"line":7,"column":120}}}))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Date de paiement :</strong> "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"paymentDate") : depth0),(depth0 != null ? lookupProperty(depth0,"locale") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":8,"column":69},"end":{"line":8,"column":102}}}))
    + "</p>\n</div>\n\n<p><strong>Détails de la facture :</strong></p>\n\n<table style=\"width: 100%; border-collapse: collapse; margin: 20px 0;\">\n  <tr style=\"border-bottom: 1px solid #ddd;\">\n    <th style=\"text-align: left; padding: 8px; background-color: #f0f0f0;\">Description</th>\n    <th style=\"text-align: right; padding: 8px; background-color: #f0f0f0;\">Montant</th>\n  </tr>\n"
    + ((stack1 = lookupProperty(helpers,"each").call(alias1,(depth0 != null ? lookupProperty(depth0,"lineItems") : depth0),{"name":"each","hash":{},"fn":container.program(0, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":18,"column":2},"end":{"line":23,"column":11}}})) != null ? stack1 : "")
    + "  <tr style=\"border-bottom: 2px solid #333;\">\n    <td style=\"padding: 8px; font-weight: bold;\">Sous-total</td>\n    <td style=\"text-align: right; padding: 8px; font-weight: bold;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"subtotal") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":26,"column":68},"end":{"line":26,"column":86}}}))
    + "</td>\n  </tr>\n  <tr style=\"border-bottom: 1px solid #ddd;\">\n    <td style=\"padding: 8px;\">Taxe d'hébergement (3.5%)</td>\n    <td style=\"text-align: right; padding: 8px;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"accommodationTax") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":30,"column":49},"end":{"line":30,"column":75}}}))
    + "</td>\n  </tr>\n  <tr style=\"border-bottom: 1px solid #ddd;\">\n    <td style=\"padding: 8px;\">TPS (5%)</td>\n    <td style=\"text-align: right; padding: 8px;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"tps") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":34,"column":49},"end":{"line":34,"column":62}}}))
    + "</td>\n  </tr>\n  <tr style=\"border-bottom: 2px solid #333;\">\n    <td style=\"padding: 8px;\">TVQ (9.975%)</td>\n    <td style=\"text-align: right; padding: 8px;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"tvq") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":38,"column":49},"end":{"line":38,"column":62}}}))
    + "</td>\n  </tr>\n  <tr>\n    <td style=\"padding: 8px; font-weight: bold; font-size: 16px;\">Total</td>\n    <td style=\"text-align: right; padding: 8px; font-weight: bold; font-size: 16px;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"total") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":42,"column":85},"end":{"line":42,"column":100}}}))
    + "</td>\n  </tr>\n</table>\n\n<p>Merci de votre confiance.</p>\n\n<p>Cordialement,<br/>\nL'équipe du Vieux Pont</p>\n";
},"useData":true}), en: Handlebars.template({"0":function(container,depth0,helpers,partials,data) {
    var alias1=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "  <tr style=\"border-bottom: 1px solid #ddd;\">\n    <td style=\"padding: 8px;\">"
    + alias1(container.lambda((depth0 != null ? lookupProperty(depth0,"description") : depth0), depth0))
    + "</td>\n    <td style=\"text-align: right; padding: 8px;\">"
    + alias1((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||container.hooks.helperMissing).call(depth0 != null ? depth0 : (container.nullContext || {}),(depth0 != null ? lookupProperty(depth0,"amount") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":21,"column":49},"end":{"line":21,"column":70}}}))
    + "</td>\n  </tr>\n";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<p>Thank you for your payment, "
    + alias4(((helper = (helper = lookupProperty(helpers,"name") || (depth0 != null ? lookupProperty(depth0,"name") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"name","hash":{},"data":data,"loc":{"start":{"line":1,"column":31},"end":{"line":1,"column":39}}}) : helper)))
    + " !</p>\n\n<p>Here is your invoice receipt:</p>\n\n<div style=\"background-color: #f0f0f0; padding: 15px; border-radius: 4px; margin: 20px 0;\">\n  <p style=\"margin: 0 0 10px 0;\"><strong>Invoice number:</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"invoiceNumber") || (depth0 != null ? lookupProperty(depth0,"invoiceNumber") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"invoiceNumber","hash":{},"data":data,"loc":{"start":{"line":6,"column":66},"end":{"line":6,"column":83}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Dates:</strong> "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkIn") : depth0),(depth0 != null ? lookupProperty(depth0,"locale") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":7,"column":57},"end":{"line":7,"column":86}}}))
    + " - "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkOut") : depth0),(depth0 != null ? lookupProperty(depth0,"locale") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":7,"column":89},"end":{"line":7,"column":119}}}))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Payment date:</strong> "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"paymentDate") : depth0),(depth0 != null ? lookupProperty(depth0,"locale") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":8,"column":64},"end":{"line":8,"column":97}}}))
    + "</p>\n</div>\n\n<p><strong>Invoice details:</strong></p>\n\n<table style=\"width: 100%; border-collapse: collapse; margin: 20px 0;\">\n  <tr style=\"border-bottom: 1px solid #ddd;\">\n    <th style=\"text-align: left; padding: 8px; background-color: #f0f0f0;\">Description</th>\n    <th style=\"text-align: right; padding: 8px; background-color: #f0f0f0;\">Amount</th>\n  </tr>\n"
    + ((stack1 = lookupProperty(helpers,"each").call(alias1,(depth0 != null ? lookupProperty(depth0,"lineItems") : depth0),{"name":"each","hash":{},"fn":container.program(0, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":18,"column":2},"end":{"line":23,"column":11}}})) != null ? stack1 : "")
    + "  <tr style=\"border-bottom: 2px solid #333;\">\n    <td style=\"padding: 8px; font-weight: bold;\">Subtotal</td>\n    <td style=\"text-align: right; padding: 8px; font-weight: bold;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"subtotal") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":26,"column":68},"end":{"line":26,"column":86}}}))
    + "</td>\n  </tr>\n  <tr style=\"border-bottom: 1px solid #ddd;\">\n    <td style=\"padding: 8px;\">Accommodation tax (3.5%)</td>\n    <td style=\"text-align: right; padding: 8px;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"accommodationTax") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":30,"column":49},"end":{"line":30,"column":75}}}))
    + "</td>\n  </tr>\n  <tr style=\"border-bottom: 1px solid #ddd;\">\n    <td style=\"padding: 8px;\">GST (5%)</td>\n    <td style=\"text-align: right; padding: 8px;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"tps") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":34,"column":49},"end":{"line":34,"column":62}}}))
    + "</td>\n  </tr>\n  <tr style=\"border-bottom: 2px solid #333;\">\n    <td style=\"padding: 8px;\">QST (9.975%)</td>\n    <td style=\"text-align: right; padding: 8px;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"tvq") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":38,"column":49},"end":{"line":38,"column":62}}}))
    + "</td>\n  </tr>\n  <tr>\n    <td style=\"padding: 8px; font-weight: bold; font-size: 16px;\">Total</td>\n    <td style=\"text-align: right; padding: 8px; font-weight: bold; font-size: 16px;\">"
    + alias4((lookupProperty(helpers,"money")||(depth0 && lookupProperty(depth0,"money"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"total") : depth0),{"name":"money","hash":{},"data":data,"loc":{"start":{"line":42,"column":85},"end":{"line":42,"column":100}}}))
    + "</td>\n  </tr>\n</table>\n\n<p>Thank you for your business.</p>\n\n<p>Best regards,<br/>\nThe Vieux Pont team</p>\n";
},"useData":true}) },
  "review-request": { fr: Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<p>Bonjour "
    + alias4(((helper = (helper = lookupProperty(helpers,"firstName") || (depth0 != null ? lookupProperty(depth0,"firstName") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"firstName","hash":{},"data":data,"loc":{"start":{"line":1,"column":11},"end":{"line":1,"column":24}}}) : helper)))
    + ",</p>\n\n<p>Merci d'avoir séjourné à L'Auberge du Vieux Pont !</p>\n\n<p>Nous aimerions connaître votre avis sur votre expérience. Votre retour nous aide à améliorer nos services.</p>\n\n<div style=\"background-color: #f0f0f0; padding: 15px; border-radius: 4px; margin: 20px 0;\">\n  <p style=\"margin: 0 0 10px 0;\"><strong>Chambre :</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"roomLabel") || (depth0 != null ? lookupProperty(depth0,"roomLabel") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"roomLabel","hash":{},"data":data,"loc":{"start":{"line":8,"column":60},"end":{"line":8,"column":73}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0;\"><strong>Dates :</strong> "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkIn") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":9,"column":49},"end":{"line":9,"column":71}}}))
    + " - "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkOut") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":9,"column":74},"end":{"line":9,"column":97}}}))
    + "</p>\n</div>\n\n<p style=\"text-align: center; margin: 20px 0;\">\n  <a href=\""
    + alias4(((helper = (helper = lookupProperty(helpers,"reviewUrl") || (depth0 != null ? lookupProperty(depth0,"reviewUrl") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"reviewUrl","hash":{},"data":data,"loc":{"start":{"line":13,"column":11},"end":{"line":13,"column":24}}}) : helper)))
    + "\" style=\"display: inline-block; padding: 12px 30px; background-color: #9d4300; color: white; text-decoration: none; border-radius: 4px; font-weight: bold;\">Laisser un avis</a>\n</p>\n\n<p>Merci !</p>\n\n<p>Cordialement,<br/>\nL'équipe du Vieux Pont</p>\n";
},"useData":true}), en: Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<p>Hello "
    + alias4(((helper = (helper = lookupProperty(helpers,"firstName") || (depth0 != null ? lookupProperty(depth0,"firstName") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"firstName","hash":{},"data":data,"loc":{"start":{"line":1,"column":9},"end":{"line":1,"column":22}}}) : helper)))
    + ",</p>\n\n<p>Thank you for staying at L'Auberge du Vieux Pont!</p>\n\n<p>We would like to know your thoughts about your experience. Your feedback helps us improve our services.</p>\n\n<div style=\"background-color: #f0f0f0; padding: 15px; border-radius: 4px; margin: 20px 0;\">\n  <p style=\"margin: 0 0 10px 0;\"><strong>Room:</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"roomLabel") || (depth0 != null ? lookupProperty(depth0,"roomLabel") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"roomLabel","hash":{},"data":data,"loc":{"start":{"line":8,"column":56},"end":{"line":8,"column":69}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0;\"><strong>Dates:</strong> "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkIn") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":9,"column":48},"end":{"line":9,"column":70}}}))
    + " - "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkOut") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":9,"column":73},"end":{"line":9,"column":96}}}))
    + "</p>\n</div>\n\n<p style=\"text-align: center; margin: 20px 0;\">\n  <a href=\""
    + alias4(((helper = (helper = lookupProperty(helpers,"reviewUrl") || (depth0 != null ? lookupProperty(depth0,"reviewUrl") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"reviewUrl","hash":{},"data":data,"loc":{"start":{"line":13,"column":11},"end":{"line":13,"column":24}}}) : helper)))
    + "\" style=\"display: inline-block; padding: 12px 30px; background-color: #9d4300; color: white; text-decoration: none; border-radius: 4px; font-weight: bold;\">Leave a review</a>\n</p>\n\n<p>Thank you!</p>\n\n<p>Best regards,<br/>\nThe Vieux Pont team</p>\n";
},"useData":true}) },
  "room-assigned": { fr: Handlebars.template({"0":function(container,depth0,helpers,partials,data) {
    var helper, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<div style=\"background-color: #fff4ec; border: 1px solid #ffb690; padding: 16px; border-radius: 4px; margin: 20px 0; text-align: center;\">\n  <p style=\"margin: 0 0 6px 0; color: #45464d; font-size: 13px;\">Code d'accès de votre chambre</p>\n  <p style=\"margin: 0; font-size: 24px; font-weight: bold; letter-spacing: 2px; color: #9d4300;\">"
    + container.escapeExpression(((helper = (helper = lookupProperty(helpers,"passkey") || (depth0 != null ? lookupProperty(depth0,"passkey") : depth0)) != null ? helper : container.hooks.helperMissing),(typeof helper === "function" ? helper.call(depth0 != null ? depth0 : (container.nullContext || {}),{"name":"passkey","hash":{},"data":data,"loc":{"start":{"line":15,"column":97},"end":{"line":15,"column":108}}}) : helper)))
    + "</p>\n</div>\n<p>Utilisez ce code pour déverrouiller la porte de votre chambre à votre arrivée.</p>\n";
},"1":function(container,depth0,helpers,partials,data) {
    return "<p>Veuillez utiliser la clé qui se trouve dans la porte de votre chambre.</p>\n";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<p>Bonjour "
    + alias4(((helper = (helper = lookupProperty(helpers,"name") || (depth0 != null ? lookupProperty(depth0,"name") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"name","hash":{},"data":data,"loc":{"start":{"line":1,"column":11},"end":{"line":1,"column":19}}}) : helper)))
    + ",</p>\n\n<p>Votre chambre a été assignée pour votre séjour.</p>\n\n<div style=\"background-color: #f0f0f0; padding: 15px; border-radius: 4px; margin: 20px 0;\">\n  <p style=\"margin: 0 0 10px 0;\"><strong>Numéro de confirmation :</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"confirmationCode") || (depth0 != null ? lookupProperty(depth0,"confirmationCode") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"confirmationCode","hash":{},"data":data,"loc":{"start":{"line":6,"column":75},"end":{"line":6,"column":95}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Chambre :</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"roomLabel") || (depth0 != null ? lookupProperty(depth0,"roomLabel") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"roomLabel","hash":{},"data":data,"loc":{"start":{"line":7,"column":60},"end":{"line":7,"column":73}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Arrivée :</strong> "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkIn") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":8,"column":60},"end":{"line":8,"column":82}}}))
    + "</p>\n  <p style=\"margin: 0;\"><strong>Départ :</strong> "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkOut") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":9,"column":50},"end":{"line":9,"column":73}}}))
    + "</p>\n</div>\n\n"
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,(depth0 != null ? lookupProperty(depth0,"passkeyEnabled") : depth0),{"name":"if","hash":{},"fn":container.program(0, data, 0),"inverse":container.program(1, data, 0),"data":data,"loc":{"start":{"line":12,"column":0},"end":{"line":20,"column":7}}})) != null ? stack1 : "")
    + "\n<p>Nous avons hâte de vous accueillir !</p>\n\n<p>Cordialement,<br/>\nL'équipe du Vieux Pont</p>\n";
},"useData":true}), en: Handlebars.template({"0":function(container,depth0,helpers,partials,data) {
    var helper, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<div style=\"background-color: #fff4ec; border: 1px solid #ffb690; padding: 16px; border-radius: 4px; margin: 20px 0; text-align: center;\">\n  <p style=\"margin: 0 0 6px 0; color: #45464d; font-size: 13px;\">Your room access code</p>\n  <p style=\"margin: 0; font-size: 24px; font-weight: bold; letter-spacing: 2px; color: #9d4300;\">"
    + container.escapeExpression(((helper = (helper = lookupProperty(helpers,"passkey") || (depth0 != null ? lookupProperty(depth0,"passkey") : depth0)) != null ? helper : container.hooks.helperMissing),(typeof helper === "function" ? helper.call(depth0 != null ? depth0 : (container.nullContext || {}),{"name":"passkey","hash":{},"data":data,"loc":{"start":{"line":15,"column":97},"end":{"line":15,"column":108}}}) : helper)))
    + "</p>\n</div>\n<p>Use this code to unlock your room door when you arrive.</p>\n";
},"1":function(container,depth0,helpers,partials,data) {
    return "<p>Please use the key located in your room door.</p>\n";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<p>Hello "
    + alias4(((helper = (helper = lookupProperty(helpers,"name") || (depth0 != null ? lookupProperty(depth0,"name") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"name","hash":{},"data":data,"loc":{"start":{"line":1,"column":9},"end":{"line":1,"column":17}}}) : helper)))
    + ",</p>\n\n<p>Your room has been assigned for your stay.</p>\n\n<div style=\"background-color: #f0f0f0; padding: 15px; border-radius: 4px; margin: 20px 0;\">\n  <p style=\"margin: 0 0 10px 0;\"><strong>Confirmation code:</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"confirmationCode") || (depth0 != null ? lookupProperty(depth0,"confirmationCode") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"confirmationCode","hash":{},"data":data,"loc":{"start":{"line":6,"column":69},"end":{"line":6,"column":89}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Room:</strong> "
    + alias4(((helper = (helper = lookupProperty(helpers,"roomLabel") || (depth0 != null ? lookupProperty(depth0,"roomLabel") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"roomLabel","hash":{},"data":data,"loc":{"start":{"line":7,"column":56},"end":{"line":7,"column":69}}}) : helper)))
    + "</p>\n  <p style=\"margin: 0 0 10px 0;\"><strong>Check-in:</strong> "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkIn") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":8,"column":60},"end":{"line":8,"column":82}}}))
    + "</p>\n  <p style=\"margin: 0;\"><strong>Check-out:</strong> "
    + alias4((lookupProperty(helpers,"formatDate")||(depth0 && lookupProperty(depth0,"formatDate"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"checkOut") : depth0),{"name":"formatDate","hash":{},"data":data,"loc":{"start":{"line":9,"column":52},"end":{"line":9,"column":75}}}))
    + "</p>\n</div>\n\n"
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,(depth0 != null ? lookupProperty(depth0,"passkeyEnabled") : depth0),{"name":"if","hash":{},"fn":container.program(0, data, 0),"inverse":container.program(1, data, 0),"data":data,"loc":{"start":{"line":12,"column":0},"end":{"line":20,"column":7}}})) != null ? stack1 : "")
    + "\n<p>We look forward to welcoming you!</p>\n\n<p>Best regards,<br/>\nThe Vieux Pont team</p>\n";
},"useData":true}) },
};
