import type { Handle } from '@sveltejs/kit';

/**
 * Security headers for the SPA.
 *
 * Content-Security-Policy is deliberately NOT set here. It is generated by
 * SvelteKit from the `kit.csp` block in svelte.config.js, because SvelteKit
 * emits an inline bootstrap script to start hydration and only the build step
 * can compute that script's hash.
 *
 * A hand-written `script-src 'self' https://js.stripe.com` used to live here.
 * It blocked that bootstrap, so every non-prerendered route was inert on direct
 * navigation or hard reload — `/admin` rendered an empty body, and guests
 * following a review link sat on "Vérification de votre invitation…" forever.
 * The header string looked correct, which is why a header-only test never
 * caught it. Do not reintroduce a CSP here: two CSP headers are enforced as
 * their intersection, so a hand-written script-src would block the hashed
 * bootstrap again even with kit.csp configured correctly.
 *
 * - `X-Frame-Options: DENY` complements `frame-ancestors 'none'` for older
 *   browsers, and still applies to responses SvelteKit's CSP does not cover.
 */
const SECURITY_HEADERS: Record<string, string> = {
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
  'Cross-Origin-Opener-Policy': 'same-origin',
};

export const handle: Handle = async ({ event, resolve }) => {
  const response = await resolve(event);
  for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
    response.headers.set(name, value);
  }
  return response;
};
