// Precompile Handlebars email templates into template *specs* at build time.
//
// Cloudflare Workers' V8 isolate forbids runtime code generation
// (`new Function`/`eval` → "Code generation from strings disallowed"). Handlebars'
// `compile()` uses `new Function`, so it cannot run in the deployed Worker. Instead
// we precompile every .hbs here (in Node, at build time) into template specs whose
// functions are baked into the bundle, and render them with `handlebars/runtime`,
// which never generates code from strings.
//
// Output: src/emails/precompiled.ts (checked in; regenerated by `pretest` and by the
// wrangler `build.command` before every dev/deploy so it can never go stale in prod).

import Handlebars from "handlebars";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const emailsDir = join(here, "..", "emails");
const outFile = join(here, "..", "src", "emails", "precompiled.ts");

const LOCALES = ["fr", "en"];
const KEYS = [
  "welcome",
  "password-reset",
  "reservation-confirmation",
  "reservation-cancellation",
  "invoice-receipt",
  "review-request",
  "room-assigned",
  "ota-welcome",
  "email-verification",
  "email-change-alert",
  "email-change-confirm",
];

const read = (rel) => readFileSync(join(emailsDir, rel), "utf8");
// Handlebars.precompile returns a JS object-literal string (the template spec).
const spec = (src) => Handlebars.precompile(src);
const wrap = (s) => `Handlebars.template(${s})`;

const base = spec(read("base.hbs"));

const partials = LOCALES.map(
  (loc) =>
    `  ${loc}: { header: ${wrap(spec(read(`partials/header.${loc}.hbs`)))}, footer: ${wrap(
      spec(read(`partials/footer.${loc}.hbs`)),
    )} },`,
).join("\n");

const templates = KEYS.map((key) => {
  const fr = wrap(spec(read(`templates/${key}.fr.hbs`)));
  const en = wrap(spec(read(`templates/${key}.en.hbs`)));
  return `  ${JSON.stringify(key)}: { fr: ${fr}, en: ${en} },`;
}).join("\n");

const out = `/* eslint-disable */
// @ts-nocheck
// AUTO-GENERATED by scripts/precompile-emails.mjs — DO NOT EDIT BY HAND.
// Handlebars templates precompiled to specs so the Worker never calls new Function()
// (Cloudflare Workers forbid runtime code generation). Rendered via handlebars/runtime.
import Handlebars from "handlebars/runtime";
import type { Locale, TemplateKey } from "./templates";

export const BASE = ${wrap(base)};

export const PARTIALS: Record<Locale, { header: HandlebarsTemplateDelegate; footer: HandlebarsTemplateDelegate }> = {
${partials}
};

export const TEMPLATES: Record<TemplateKey, Record<Locale, HandlebarsTemplateDelegate>> = {
${templates}
};
`;

writeFileSync(outFile, out);
console.log(`Precompiled ${KEYS.length * 2 + 5} templates → ${outFile}`);
